"use client";
import { useCallback,useEffect,useState } from "react";
import { ArrowDown,ArrowRight,ArrowUpRight,ArrowLeft,BookOpen,Download,Pause,Play,RotateCcw,X,List,Move } from "lucide-react";
import { Tabs,TabsList,TabsTrigger,TabsContent } from "@/components/ui/tabs";
import { Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose } from "@/components/ui/dialog";
import { Slider } from "@/components/ui/slider";
import Torus from "./torus";
import chapters from "./chapters.json";
const PDF='/assets/DEMU2-Thesis.pdf';
const movements=[
 {id:'regress',label:'Regress',symbol:<>A cause.<br/>Before the cause.<br/><em>And before that?</em></>,kicker:'01 / The problem of explanation',title:'Where does explanation end?',body:'Every event can be explained by an earlier event. But a chain of earlier events still leaves a question: what explains the whole chain?',body2:'DEMU2 begins with this problem of infinite regress and asks whether Nature could carry its explanation within its own structure.',chapter:6},
 {id:'motion',label:'Motion',symbol:<>An origin.<br/><em>Without a beginning.</em></>,kicker:'02 / Timelessness and activity',title:'Does motion need a first moment?',body:'Pettersen proposes that motion and motionlessness are aspects of one reality. What appears timeless at the foundation can be experienced as change within the universe.',body2:'On this account, the origin is a structural relationship, rather than a first event in a sequence of time.',chapter:4},
 {id:'balance',label:'Balance',symbol:<>Expansion<br/><em>= contraction</em></>,kicker:'03 / One reciprocal operation',title:'A balance that includes everything.',body:'The proposed model treats expansion and contraction as reciprocal aspects of one process. The dual torus gives this relationship a geometric expression.',body2:'The argument asks what follows if that balance must hold throughout the entire circulation, including everything returning to the foundation.',chapter:9},
 {id:'renewal',label:'Renewal',symbol:<>What returns<br/><em>can begin again.</em></>,kicker:'04 / Entropy and renewed energy',title:'Could balance require renewal?',body:'Pettersen argues that indefinitely accumulated entropy would undermine the proposed global balance. He therefore develops a philosophical argument for entropy reset.',body2:'The book then asks whether renewed matter and energy could offer a continually replenished source of usable energy. How such access could be established remains a question for investigation.',chapter:11},
 {id:'consciousness',label:'Consciousness',symbol:<>Nature,<br/><em>from within.</em></>,kicker:'05 / The closure of Nature',title:'Where does consciousness belong?',body:'The inquiry extends from motion and energy to the character of reality itself. Pettersen argues that consciousness is fundamental to Nature’s explanatory closure.',body2:'Later chapters explore the consequences of that proposal for identity, free will, God, and the meaning of life.',chapter:18}
];
function Mark(){return <svg viewBox="0 0 25 27" fill="none" aria-hidden="true"><path d="M12.5 2 24 25H1Z" stroke="currentColor" strokeWidth="1.2"/><path d="m12.5 9 7.5 15H5Z" fill="currentColor" opacity=".65"/></svg>}
function Stars(){return <svg width="72" height="25" viewBox="0 0 72 25" fill="currentColor" aria-hidden="true">{[12,36,60].map(x=><path key={x} d={`M${x} 1Q${x+1} 11 ${x+11} 12Q${x+1} 13 ${x} 24Q${x-1} 13 ${x-11} 12Q${x-1} 11 ${x} 1Z`}/>)}</svg>}
export default function Home(){
 const [playing,setPlaying]=useState(true),[speed,setSpeed]=useState(1),[reset,setReset]=useState(0),[movement,setMovement]=useState('regress');
 const [reader,setReader]=useState(false),[chapter,setChapter]=useState(0),[mobileContents,setMobileContents]=useState(false);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');if(media.matches)setPlaying(false);const change=()=>{if(media.matches)setPlaying(false)};media.addEventListener('change',change);return()=>media.removeEventListener('change',change)},[]);
 const readChapter=useCallback((number:number)=>{if(!Number.isInteger(number)||number<0||number>25)throw new Error('Choose a chapter from 1 to 25, or 0 for the contents.');setChapter(number);setReader(true);setMobileContents(false)},[]);
 const toggleMotion=useCallback(()=>setPlaying(p=>!p),[]);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options?:unknown)=>unknown}}).modelContext;
  if(!context?.registerTool)return;const abort=new AbortController();
  const tools=[
   {name:'open_demu2_chapter',title:'Open a DEMU2 chapter',description:'Open the thesis reader at chapter 1–25, or 0 for its table of contents.',inputSchema:{type:'object',properties:{chapter:{type:'integer',minimum:0,maximum:25}},required:['chapter'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:{chapter:number})=>{readChapter(input.chapter);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {chapter:input.chapter,page:input.chapter===0?5:chapters[input.chapter-1].page,readerOpen:true}}},
   {name:'explore_demu2_argument',title:'Explore the DEMU2 argument',description:'Select and display one of the five movements of the philosophical argument.',inputSchema:{type:'object',properties:{movement:{type:'string',enum:movements.map(m=>m.id)}},required:['movement'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:{movement:string})=>{if(!movements.some(m=>m.id===input.movement))throw new Error('Unknown movement');setMovement(input.movement);document.getElementById('argument')?.scrollIntoView({behavior:'instant'});await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {movement:input.movement}}}
  ];
  tools.forEach(t=>{try{Promise.resolve(context.registerTool(t,{signal:abort.signal})).catch(()=>{})}catch{}});return()=>abort.abort();
 },[readChapter]);
 const page=chapter===0?5:chapters[chapter-1].page;
 return <div className="site-shell">
  <a className="skip-link" href="#argument">Skip to the argument</a>
  <header className="site-header"><a href="#" className="brand" aria-label="DEMU2 home"><Mark/>DEMU2</a><nav className="site-nav" aria-label="Main navigation"><a href="#argument">The argument</a><a href="#thesis">The thesis</a><a href="#author">The author</a><button className="nav-reader" onClick={()=>readChapter(0)}>Read DEMU2 <ArrowUpRight className="icon"/></button></nav></header>
  <main>
  <section className="hero" aria-labelledby="hero-title">
   <div className="hero-copy read-reveal"><p className="eyebrow">An inquiry into the nature of reality</p><h1 id="hero-title">Beyond the<br/><em>first cause.</em></h1><p className="hero-intro">What if Nature has an origin, but no beginning?<br/>Explore a philosophical argument for timeless balance, consciousness, and the possibility of new energy.</p><div className="hero-actions"><a className="primary-button" href="#argument">Explore the argument <ArrowDown className="icon"/></a><button className="text-button" onClick={()=>readChapter(0)}><BookOpen className="icon"/>Read the thesis</button></div><p className="hero-byline">DEMU2 · Thor Fabian Pettersen</p></div>
   <div className="hero-visual"><div className="orbit-badge">The geometry of balance</div><Torus playing={playing} speed={speed} reset={reset} onPause={toggleMotion}/><div className="visual-caption">RECIPROCAL EXPANSION & CONTRACTION<span>Conceptual illustration · Drag or use arrow keys to rotate</span></div></div>
   <div className="hero-bottom"><a href="#argument" className="scroll-link"><ArrowDown className="icon"/>Follow the inquiry</a><span>A philosophical model of explanatory closure</span><div className="model-controls"><div className="speed-control"><span>Motion</span><Slider aria-label="Animation speed" value={[speed]} min={.25} max={2} step={.25} onValueChange={v=>setSpeed(v[0])}/></div><button onClick={toggleMotion} aria-label={playing?'Pause animation':'Play animation'}>{playing?<Pause className="icon"/>:<Play className="icon"/>}{playing?'Pause':'Play'}</button><button onClick={()=>{setReset(r=>r+1);setSpeed(1)}} aria-label="Reset model view"><RotateCcw className="icon"/></button></div></div>
  </section>
  <section id="argument" className="section argument" aria-labelledby="argument-heading"><div className="section-heading"><div><span className="section-number">01 — FOLLOW THE THREAD</span><h2 id="argument-heading">Five movements.<br/>One unfolding question.</h2></div><p>Begin with the problem of explanation.<br/>Follow its implications into motion, energy,<br/>and the nature of consciousness.</p></div>
   <Tabs value={movement} onValueChange={setMovement} className="argument-tabs"><TabsList className="argument-tablist" aria-label="Movements of the argument">{movements.map((m,i)=><TabsTrigger key={m.id} value={m.id} className="argument-tab"><span>0{i+1}</span>{m.label}</TabsTrigger>)}</TabsList>{movements.map(m=><TabsContent key={m.id} value={m.id}><div className="argument-body"><div className="argument-symbol">{m.symbol}<small>{m.kicker}</small></div><div className="argument-prose"><h3>{m.title}</h3><p>{m.body}</p><p>{m.body2}</p><button className="text-button" onClick={()=>readChapter(m.chapter)}>Continue in chapter {m.chapter}<ArrowUpRight className="icon"/></button></div></div></TabsContent>)}</Tabs>
   <div className="argument-footer"><span>These are the author’s philosophical proposals, presented for exploration and critical discussion.</span><div className="step-progress" aria-hidden="true">{movements.map(m=><span key={m.id} className={m.id===movement?'active':''}/>)}</div></div>
  </section>
  <section id="thesis" className="section book-section" aria-labelledby="thesis-heading"><div className="section-heading"><div><span className="section-number">02 — GO DEEPER</span><h2 id="thesis-heading">The complete inquiry.</h2></div><p>Infinite Regress and the Possibility of New Energy.<br/>A philosophical investigation of explanatory closure and entropy reset.</p></div><div className="book-layout"><div className="book-object"><img className="book-cover" src="/assets/demu2-cover.png" width="2475" height="3300" alt="DEMU2 book cover with a copper and silver triangle, by Thor Fabian Pettersen" loading="lazy"/><div className="book-meta"><span>25 CHAPTERS</span><span>246 PAGES</span><span>ENGLISH</span></div><div className="book-buttons"><button className="primary-button" onClick={()=>readChapter(0)}>Open the reader <BookOpen className="icon"/></button><a className="text-button" href={PDF} download="DEMU2-Thesis.pdf"><Download className="icon"/>Download PDF</a></div></div><div><div className="index-heading"><span>Table of contents</span><span>Page</span></div><div className="chapter-index" tabIndex={0} aria-label="Browse all 25 chapters">{chapters.map(ch=><button className="chapter-row" key={ch.number} onClick={()=>readChapter(ch.number)}><span className="chapter-no">{String(ch.number).padStart(2,'0')}</span><span className="chapter-title">{ch.title}</span><span className="chapter-page">{ch.printedPage}</span></button>)}</div><p className="reader-note"><Move size={14}/>Scroll to explore all chapters. Select one to begin reading.</p></div></div></section>
  <section id="author" className="closing"><p className="eyebrow">A thought to carry with you</p><blockquote>“Time began from<br/><em>light’s point of view.</em>”</blockquote><p>From the epigraph to DEMU2</p><div className="author-line"><Stars/><span>Thor Fabian Pettersen<br/><small>Author of DEMU2</small></span></div></section>
  </main>
  <footer className="site-footer"><a className="footer-brand" href="#">DEMU2</a><p>An independent philosophical inquiry by Thor Fabian Pettersen.</p><div className="footer-end"><a href={PDF} download>Download thesis</a><a href="#">Back to top ↑</a></div></footer>
  <Dialog open={reader} onOpenChange={setReader}><DialogContent className="reading-dialog" showCloseButton={false}><div className="reading-topbar"><div><DialogTitle className="reader-title">DEMU2 · The thesis</DialogTitle><DialogDescription className="reader-subtitle">{chapter===0?'Table of contents':`Chapter ${chapter} · ${chapters[chapter-1].title}`}</DialogDescription></div><a className="reader-download" href={PDF} download><Download className="icon"/>Download PDF</a><button className="reader-mobile-menu" onClick={()=>setMobileContents(m=>!m)} aria-expanded={mobileContents}><List className="icon"/>Contents</button><DialogClose asChild><button className="close-reader" aria-label="Close reader"><X className="icon"/></button></DialogClose></div><div className="reader-body"><nav className={`reader-index ${mobileContents?'mobile-open':''}`} aria-label="Reader chapters"><button onClick={()=>readChapter(0)} className={chapter===0?'current':''}><List size={17}/>Table of contents</button>{chapters.map(ch=><button key={ch.number} onClick={()=>readChapter(ch.number)} className={chapter===ch.number?'current':''} aria-current={chapter===ch.number?'page':undefined}><span>{String(ch.number).padStart(2,'0')}</span>{ch.title}</button>)}</nav><div className="pdf-area"><iframe key={page} title={chapter===0?'DEMU2 table of contents':`DEMU2 chapter ${chapter}`} className="pdf-frame" src={`${PDF}#page=${page}&view=FitH&navpanes=0`}/><div className="reader-help"><span>Page numbers in the PDF return to the contents. <a href={`${PDF}#page=${page}`} target="_blank" rel="noopener noreferrer">Open PDF separately</a></span><div className="reader-chapter-nav"><button onClick={()=>readChapter(chapter-1)} disabled={chapter===0}><ArrowLeft size={14}/>Previous</button><button onClick={()=>readChapter(chapter+1)} disabled={chapter===25}>Next chapter<ArrowRight size={14}/></button></div></div></div></div></DialogContent></Dialog>
 </div>
}
